import type { Metadata } from "next";
import {Lora, Sofia_Sans} from "next/font/google"; 
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const lora = Lora ({
  variable: "--font-lora",
  weight: ["700"],
});

const sofia_sans = Sofia_Sans ({
  variable: "--font-sofia-sans",
  weight: ["400", "700"], 
});

export const metadata: Metadata = {
  title: "Xero Crypto",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${lora.variable} ${sofia_sans.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}